version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: proyectogopiniones_postgres
    restart: always
    environment:
      POSTGRES_DB: ProyectoGOpiniones
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
    - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgressql/data

volumes:
  postgres_data:

